### ISSUE TITLE
Stop considering "Route has no stops" a critical error

### ISSUE THREAD

**Issue by alexey-zakharenkov** [alexey-zakharenkov/subways#16]
When a new subway line is opened or its construction is started, mappers often create a route relation only with tracks (without stations), or with stations all of which are tagged under construction. Currently the validator paints such a city red with "Route has no stops" error message. Need to assign such issues the "warning" severity to not prevent building routable subway network.

**Comment by Zverik** [comment]
Did you try convincing them to use `type=construction:route` for the relation?

**Comment by Zverik** [comment]
Thing is, while this change might help in a few rare cities with no subway lines, it downscales real errors in cities that have those. Mappers in OSM are eager to map things that are not there. A route relation is a route, first and foremost. When there are no working subway routes, they should not map any.

**Comment by alexey-zakharenkov** [comment]
In fact, the issue was inspired by chinese metro with many planned and constructed lines and pretty high mappers activity in the subway layer, as well as with occasional route=network => route=subway/train/... retagging.

The goal is to have as much as possible good cities at any moment during an app's data update, provided there is no responsible person who would monitor and support subway quality level near 100%.

> it downscales real errors

By definition, the validation _warning_ is an **error** in data that doesn't prevent a network to be used in an app for rendering/routing. I think wrongly tagged route relation is about this. **Found lines count != expected lines count** still remains a critical error. 

@Zverik Ilya, do you still oppose the suggestion?
