### ISSUE TITLE
Error number of stations

### ISSUE THREAD

**Issue by matheusgomesms** [alexey-zakharenkov/subways#37]
Hi there!

I just updated OSM adding a new station in my town (Fortaleza-Brazil), but the validator throws the error: Found 41 stations in routes, expected 40.

How do we update the expected number of stations? I tried to find in many places, but I am not sure where. I also commented in a spreadsheet that I found, but again, not sure if that was the place.

Thanks!

**Comment by alexey-zakharenkov** [comment]
Hi Matheus!
Thank you for your interest and contribution.
Yeap, expected number of station should be corrected in the spreadsheet. You see, it's alright now.
