### ISSUE TITLE
Can't handle with circular metro lines' inner and outer loops

### ISSUE THREAD

**Issue by LaoshuBaby** [alexey-zakharenkov/subways#46]
For example, there are circular lines in [China](https://web.archive.org/web/20231211050943/https://cdn.organicmaps.app/subway/china.html) and [Russia](https://web.archive.org/web/20230920174419/https://cdn.organicmaps.app/subway/russia.html):

* Beijing Line 2: https://www.openstreetmap.org/relation/1667236
* Beijing Line 10: https://www.openstreetmap.org/relation/1721075
* Chengdu Line 7: https://www.openstreetmap.org/relation/7913593
* Moscow Circular Line: https://www.openstreetmap.org/relation/300607

And all of them have a complete route_master (which have completed 2 loops' relation), but currently the checker give a warning like that:

> Only one route in route_master. Please check if it needs a return route ([relation 1667236](https://www.openstreetmap.org/relation/1667236), "地铁 2号线: 西直门 -> 西直门（内环）")

**Comment by alexey-zakharenkov** [comment]
Thank you. Most probably it's because OSM route relations for inner/outer loops start at different stations. I'll take it to work.
